# This will deploy Quay with Clair automatically on the url quay.app.example.com while keeping the configuration to update it
#    sslCertificatesSecretName: custom-quay-ssl

apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    keepConfigDeployment: true
    externalAccessType: Route
    migrationPhase: new-installation
    routeHost: quay.apps.ocpws.kee.vizuri.com
    hostname: quay.apps.ocpws.kee.vizuri.com
    database:
      volumeSize: 10Gi
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
