apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpassidp
    type: HTPasswd
    mappingMethod: claim 
    htpasswd:
      fileData:
        name: workshop-user-secret

