- name: Setup CI/CD Workshop Class
  hosts: 127.0.0.1
  connection: local
#  hosts: config
#  become: true

  vars:
    aws_region: us-east-1
    students_start: 1
    students_end: 1
    working_dir: working
    html_dir: html
    workshop_dns_zone: kee.vizuri.com
    ocp_app_suffix: apps.ocpws.kee.vizuri.com
    ocp_console_url: https://console-openshift-console.apps.ocpws.kee.vizuri.com
    ocp_api_url: https://api.ocpws.kee.vizuri.com:6443
    ec2_name_prefix: devsecops
    ec2_region: us-east-1
    s3_state: present
    student_prefix: student
    #student_prefix: user
    student_pwd: workshop1!
    lab_dirs:
     - Exercise-1
     - Exercise-2
     - Exercise-3
     - Exercise-4
     - Exercise-5
     - Exercise-6
     - Exercise-7
     - Exercise-8
     - Exercise-9
     - Exercise-10
     - Exercise-11

  tasks:
  - name: CREATE STUDENT WEBPAGE
    template:
      src: ./templates/index.html.j2
      dest: "{{ playbook_dir }}/webpage/{{ ec2_name_prefix|lower }}-index.html"
    when: s3_state == 'present'

  - name: CREATE S3 BUCKET
    s3_bucket:
      name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"
      state: "{{ s3_state }}"
      region: "{{aws_region}}"
      force: yes

  - name: ENABLE WEB HOSTING
    s3_website:
     name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"
     state: "{{ s3_state }}"
     region: "{{aws_region}}"
     suffix: "{{ ec2_name_prefix|lower }}-index.html"
    register: s3_site
    when: s3_state == 'present'
  
  - name: DNS FOR STUDENT WEBPAGE FOR US-EAST-1
    route53:
      state: "{{ s3_state }}"
      zone: "{{workshop_dns_zone}}"
      record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
      type: CNAME
      overwrite: yes
      value: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}.s3-website-{{aws_region}}.amazonaws.com"
    when:
      - aws_region == 'us-east-1'
  
  - name: DNS FOR WEBPAGE
    route53:
      state: "{{ s3_state }}"
      zone: "{{workshop_dns_zone}}"
      record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
      type: CNAME
      overwrite: yes
      value: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}.s3-website.{{aws_region}}.amazonaws.com"
    when:
      - aws_region != 'us-east-1'
  
  - name: PUT STUDENT WEBPAGE
    s3_sync:
      bucket: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
      region: "{{aws_region}}"
      file_root: "{{ playbook_dir }}/webpage"
      mime_map:
        .html: text/html
      permission: public-read
      include: "{{ ec2_name_prefix|lower }}-index.html"
    when: s3_state == 'present'
  
  - include_tasks: setup-student-website.yml 
    with_items: "{{ lookup('sequence','start='+students_start|string + ' end='+students_end|string,wantlist=True) }}"
    loop_control:
      loop_var: student_number

  - name: Delete working directories
    file:
      path: '{{ working_dir }}'
      state: absent
    with_items:
     - '{{ working_dir }}'
     - '{{ html_dir }}'
